package com.sal.prompt.web.model.lookup;

public enum DSDPOLookupEnum {
    DSD_PO_ACTION,
    DSD_PO_ACTION_UPDATE,
    DSD_PO_IMPORT_SOURCE,
    DSD_PO_APPROVAL_ACTION,
    DSD_PO_DOC_TYPE_CODE,
    DSD_PO_PRC_BU,
    DSD_PO_REQ_BU,
    DSD_PO_SOLD_TO_LEGAL_ENTITY,
    DSD_PO_BILL_BU,
    DSD_PO_CURRENCY_CODE,
    DSD_PO_BILL_TO_LOC,
    DSD_PO_REQU_ACK,
    DSD_PO_ATTRIBUTE_CAT,
    DSD_PO_DEF_BUYER
}
