//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.11 at 11:40:35 PM IST 
//


package com.sal.prompt.web.client.soap.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CatalogContents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogContents"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="catalogContents" type="{http://xmlns.oracle.com/oxp/service/PublicReportService}ArrayOfItemData"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogContents", propOrder = {
    "catalogContents"
})
public class CatalogContents {

    @XmlElement(required = true, nillable = true)
    protected ArrayOfItemData catalogContents;

    /**
     * Gets the value of the catalogContents property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemData }
     *     
     */
    public ArrayOfItemData getCatalogContents() {
        return catalogContents;
    }

    /**
     * Sets the value of the catalogContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemData }
     *     
     */
    public void setCatalogContents(ArrayOfItemData value) {
        this.catalogContents = value;
    }

}
