//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.10 at 11:18:18 PM IST 
//


package com.sal.prompt.web.client.soap.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reportObjectAbsolutePathURL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="objectType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="objectZippedData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportObjectAbsolutePathURL",
    "objectType",
    "objectZippedData"
})
@XmlRootElement(name = "uploadReportObject")
public class UploadReportObject {

    @XmlElement(required = true)
    protected String reportObjectAbsolutePathURL;
    @XmlElement(required = true)
    protected String objectType;
    @XmlElement(required = true)
    protected byte[] objectZippedData;

    /**
     * Gets the value of the reportObjectAbsolutePathURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportObjectAbsolutePathURL() {
        return reportObjectAbsolutePathURL;
    }

    /**
     * Sets the value of the reportObjectAbsolutePathURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportObjectAbsolutePathURL(String value) {
        this.reportObjectAbsolutePathURL = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the objectZippedData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getObjectZippedData() {
        return objectZippedData;
    }

    /**
     * Sets the value of the objectZippedData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setObjectZippedData(byte[] value) {
        this.objectZippedData = value;
    }

}
